monolog:
    handlers:
        uncaught_exceptions:
            type: stream
            path: '%kernel.logs_dir%/uncaught_exceptions.log'
            channels: ['uncaught_exceptions']
        mailer:
            type: stream
            path: '%kernel.logs_dir%/mailer.log'
            channels: ['mailer']
